services:

  #lilypad:
  #  build:
  #    context: .
  #    dockerfile: infra/Dockerfile
  #  ports:
  #    - 8080:8080
  #entrypoint: tail -f /dev/null
  #  networks:
  #    - lilypad

  solver:
    build:
      context: .
      dockerfile: infra/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - WEB3_PRIVATE_KEY=${SOLVER_PRIVATE_KEY}
      - JOB_CREATOR_ADDRESS=${JOB_CREATOR_ADDRESS}
      - SERVICE_MEDIATORS=${MEDIATOR_ADDRESS}
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - SERVER_URL=http://10.5.0.2:8080
      - WEB3_RPC_URL=ws://geth:8546
    entrypoint: [ "lilypad", "solver" ]
    networks:
      lilypad:
        ipv4_address: 10.5.0.2
    depends_on:
      geth:
        condition: service_healthy
    env_file:
      - .env
      - .env.addr
    healthcheck:
      test: [ "CMD-SHELL", " netstat -an | grep -q 8080" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 10s

  mediator:
    build:
      context: .
      dockerfile: infra/Dockerfile
    environment:
      - WEB3_PRIVATE_KEY=${MEDIATOR_PRIVATE_KEY}
      - WEB3_DIRECTORY_ADDRESS=${DIRECTORY_ADDRESS}
      - SERVICE_SOLVER=${SOLVER_ADDRESS}
      - WEB3_RPC_URL=ws://geth:8546
    entrypoint:
      [
        "lilypad",
        "mediator",
        "--bacalhau-api-host",
        "bacalhau"
      ]
    networks:
      lilypad:
        ipv4_address: 10.5.0.3
    depends_on:
      solver:
        condition: service_healthy
    env_file:
      - .env
      - .env.addr

  resource-provider:
    build:
      context: .
      dockerfile: infra/Dockerfile
    environment:
      - WEB3_PRIVATE_KEY=${RESOURCE_PROVIDER_PRIVATE_KEY}
      - SERVICE_MEDIATORS=${MEDIATOR_ADDRESS}
      - SERVICE_SOLVER=${SOLVER_ADDRESS}
      - WEB3_RPC_URL=ws://geth:8546
    entrypoint:
      [
        "lilypad",
        "resource-provider",
        "--bacalhau-api-host",
        "bacalhau"
      ]
    networks:
      lilypad:
        ipv4_address: 10.5.0.4
    depends_on:
      solver:
        condition: service_healthy
      mediator:
        condition: service_started
    env_file:
      - .env
      - .env.addr

  jobcreator:
    build:
      context: .
      dockerfile: infra/Dockerfile
    environment:
      - WEB3_PRIVATE_KEY=${SOLVER_PRIVATE_KEY}
      - SERVICE_SOLVER=${SOLVER_ADDRESS}
      - SERVICE_MEDIATORS=${MEDIATOR_ADDRESS}
      - WEB3_RPC_URL=ws://geth:8546
    entrypoint: [ "lilypad", "jobcreator" ]
    networks:
      lilypad:
        ipv4_address: 10.5.0.5
    env_file:
      - .env
      - .env.addr

  #ipfs:
  #  image: ipfs/kubo:v0.25.0
  #  ports:
  #    - 4001:4001
  #    - 4002:4002/udp
  #    - 4003:4003
  #    - 5001:5001
  #  entrypoint: /bin/sh
  #  command: >
  #    -c "ipfs init && ipfs daemon --migrate=true --enable-gc=true --enable-pubsub-experiment"
  #  networks:
  #    lilypad:
  #      ipv4_address: 10.5.0.6
  #  env_file:
  #    - .env

  bacalhau:
    image: ghcr.io/bacalhau-project/bacalhau:v1.0.3
    ports:
      - 1234:1234
      - 1235:1235
      - 1235:1235/udp
    entrypoint: bacalhau serve --node-type compute,requester --peer none --private-internal-ipfs=false --job-selection-accept-networked
    networks:
      lilypad:
        ipv4_address: 10.5.0.7
    env_file:
      - .env

  geth:
    image: ethereum/client-go:v1.13.5
    ports:
      - "8545:8545"
      - "8546:8546"
    entrypoint: geth --datadir /data/geth --dev --ws --ws.api web3,eth,net --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins '*' --http --http.api web3,eth,net --http.addr 0.0.0.0 --http.corsdomain '*' --http.port 8545 --http.vhosts '*'
    volumes:
      - .data:/data/geth
    networks:
      lilypad:
        ipv4_address: 10.5.0.8
    healthcheck:
      #test: wget http://localhost:8545
      test: [ "CMD-SHELL", " netstat -an | grep -q 8545" ]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s
    env_file:
      - .env

networks:
  lilypad:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
